# PostgreSQL DB 설정
datasource:
  driver-class-name: "org.postgresql.Driver"
  url: "jdbc:postgresql://postgresql:5430"
  username: "local"
  password: "local"

filepath:
  persistent-volume-data: "C:\\data\\local\\"
  pod-volume-data: "C:\\data\\temp\\"