spring:
  profiles:
    active: local

server:
  port: 8080

application:
  role: "all"

filepath:
  postgresql:
  persistent-volume-data:
  temp-volume-data:

datasource:
  driver-class-name:
  url:
  username:
  password: