spring:
  profiles:
    active: local

server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true


application:
  role: "test"

datasource:
  driver-class-name: ""
  url: ""
  username: ""
  password: ""