spring:
  profiles:
    active: local

server:
  port: 8080

application:
  role: "ALL"
  version: "Api Tester v1.0.0"

datasource:
  driver-class-name:
  url:
  username:
  password:

filepath:
  postgresql:
  persistent-volume-data:
  temp-volume-data:

