spring:
  profiles:
    active: local

server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: false

database:
  username: local
  password: local
  server:
    ip: 10.10.10.0
    port: 1234